name = "request-signing-worker"
main = "src/index.js"
compatibility_date = "2024-03-10"

route = { pattern = "signedurl.whereismypacket.net/signedurl/generate/*", zone_name = "whereismypacket.net" }

compatibility_flags = ["nodejs_compat_v2"]